version: '3'

services:
  resulteer:
   image: resulteer
   ports:
     - 4040
   environment:
     - SERVICE_PORTS=4040
   deploy:
     replicas: 3
     update_config:
       parallelism: 1
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - resulteer
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay